
cal_costmap:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 0.2
    static_map: false
    rolling_window: true
    width: 5.0
    height: 5.0
    resolution: 0.01
    meter_scoring: true
